"""CI output: workflow annotations and a job summary.

Two formats, both text, both with a hostile-input problem of their own.

A GitHub workflow annotation is a single line — `::warning file=x,line=1::msg` —
and a message containing a newline does not produce a malformed annotation, it
produces *a second command*.  A finding description comes from the artifact under
examination, so that is an injection into the CI runner's control stream, and it
is why every value here goes through :func:`_escaped` rather than being
interpolated.

A job summary is Markdown rendered into a page.  The table cells come from the
same untrusted place, and a pipe in a value silently rewrites the table around
it.  Values are escaped for that too.

Neither format can carry a paragraph, so what gets kept when space runs out
matters: the annotation states what the finding does *not* establish, because a
CI log line saying "AI attribution found" is precisely the sentence someone
screenshots.
"""

from __future__ import annotations

from typing import Final

from trueai.adapters.views import (
    FindingExplanation,
    explain_findings,
    integrity_evidence,
    remediation_preview,
)
from trueai.core.models import RemediationPlan, ScanReport, Severity
from trueai.core.provenance_view import facets_for_report

#: Severities that become an error annotation rather than a warning. A CI job
#: that failed on every INFO finding would be turned off within a week.
_ERROR_SEVERITIES: Final[frozenset[Severity]] = frozenset({Severity.CRITICAL, Severity.HIGH})

#: What a workflow command treats as structure rather than as text.
_COMMAND_ESCAPES: Final[tuple[tuple[str, str], ...]] = (
    ("%", "%25"),
    ("\r", "%0D"),
    ("\n", "%0A"),
)

#: Additional characters that separate one annotation property from the next.
_PROPERTY_ESCAPES: Final[tuple[tuple[str, str], ...]] = ((":", "%3A"), (",", "%2C"))


def _escaped(value: object, *, is_property: bool = False) -> str:
    """Escape a value for a workflow command line.

    A newline in a message is not a formatting problem, it is a second command,
    so this is an injection boundary rather than a cosmetic one.
    """

    text = str(value)
    for character, replacement in _COMMAND_ESCAPES:
        text = text.replace(character, replacement)
    if is_property:
        for character, replacement in _PROPERTY_ESCAPES:
            text = text.replace(character, replacement)
    return text


def _cell(value: object) -> str:
    """Escape a value for a Markdown table cell.

    A pipe rewrites the table around it, and a newline ends the row early.
    """

    return str(value).replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def annotation(explanation: FindingExplanation, severity: Severity) -> str:
    """Return one workflow annotation for a finding."""

    level = "error" if severity in _ERROR_SEVERITIES else "warning"
    properties = [f"file={_escaped(explanation.artifact_path, is_property=True)}"]
    if explanation.line is not None:
        properties.append(f"line={explanation.line}")
        if explanation.column is not None:
            properties.append(f"col={explanation.column}")
    properties.append(f"title={_escaped(explanation.title, is_property=True)}")
    # The limit travels with the claim. A CI line reading "AI attribution found"
    # is the sentence that gets screenshotted, and the qualifier is the first
    # thing a one-line format loses unless it is put in deliberately.
    message = " ".join([explanation.evidence_summary, *explanation.does_not_claim])
    return f"::{level} {','.join(properties)}::{_escaped(message)}"


def workflow_annotations(report: ScanReport) -> tuple[str, ...]:
    """Return one annotation per finding, in report order."""

    return tuple(
        annotation(explanation, finding.severity)
        for explanation, finding in zip(explain_findings(report), report.findings, strict=True)
    )


def job_summary(report: ScanReport, plan: RemediationPlan | None = None) -> str:
    """Return a Markdown summary for a CI job page."""

    lines = [
        "## TrueAI scan",
        "",
        f"**{report.summary.finding_count}** findings across "
        f"**{report.summary.artifact_count}** artifacts. "
        "A deterministic finding means the stated trace was observed; it does not claim the "
        "artifact was generated by AI.",
        "",
    ]

    if report.findings:
        lines += [
            "| Severity | Confidence | Artifact | Finding | Does not claim |",
            "| --- | --- | --- | --- | --- |",
        ]
        for explanation, finding in zip(explain_findings(report), report.findings, strict=True):
            lines.append(
                f"| {_cell(explanation.severity)} "
                f"| {_cell(finding.confidence_type.value)} "
                f"| `{_cell(explanation.artifact_path)}` "
                f"| {_cell(explanation.title)} "
                f"| {_cell(' '.join(explanation.does_not_claim))} |"
            )
        lines.append("")
    else:
        lines += ["No findings within the detector scope that ran.", ""]

    faceted = facets_for_report(report)
    if faceted:
        lines += [
            "### Provenance",
            "",
            "| Artifact | Marker | Signature | Signer trust | Provider |",
            "| --- | --- | --- | --- | --- |",
        ]
        for item in faceted:
            answers = " | ".join(_cell(row.answer.replace("_", " ")) for row in item.rows())
            lines.append(f"| `{_cell(item.artifact_path)}` | {answers} |")
        lines.append("")

    if report.diagnostics:
        # Coverage before conclusions: a scan that could not read something did
        # not find it clean, and a summary that omits that oversells the rest.
        lines += [
            "### Coverage",
            "",
            *(
                f"- **{_cell(item.severity.value)}** `{_cell(item.code)}` {_cell(item.message)}"
                for item in report.diagnostics
            ),
            "",
        ]

    if plan is not None:
        preview = remediation_preview(plan)
        lines += [
            "### Remediation preview",
            "",
            f"- {len(preview.steps)} operations under policy `{_cell(preview.policy)}`",
            f"- {len(preview.needs_review)} findings need human review",
            f"- {len(preview.preserved)} findings preserved as evidence",
            f"- {len(preview.blocked)} findings blocked from automatic cleanup",
            "",
        ]
        if preview.changes_visible_content:
            lines += [
                "> At least one operation would change visible content. Review the result.",
                "",
            ]

    evidence = integrity_evidence(report.integrity)
    lines += ["### Integrity", "", f"`{_cell(evidence.status)}` {_cell(evidence.explanation)}", ""]
    return "\n".join(lines)


__all__ = ["annotation", "job_summary", "workflow_annotations"]
