"""One projection of a report, so three interfaces do not each invent their own.

A desktop client, a CI job, and an editor extension all need the same five
things: what a finding claims, what cleanup would do, what integrity evidence
exists, what provenance was established, and whether an audit certificate holds.
Left to themselves each surface derives those from the schema separately, and
they drift — one shows "AI-generated", another shows "attribution string
found", and they are describing the same finding.

The part worth centralising is not the formatting. It is
:attr:`FindingExplanation.does_not_claim`: the sentence saying what a finding
does **not** establish. That sentence is the project's whole discipline, it is
derivable from the confidence class and the provenance class, and it is the
first thing an interface drops when it is short of space. Deriving it here means
an interface has to actively discard it rather than simply never having had it.

Nothing here is report content. Everything is derived from
:class:`~trueai.core.models.ScanReport` and friends, so the frozen schema keeps
one source of truth.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Final

from trueai.core.certificates import AuditCertificate, CertificateVerification
from trueai.core.models import (
    ConfidenceType,
    Finding,
    IntegrityReport,
    IntegrityStatus,
    ProvenanceClass,
    Remediation,
    RemediationPlan,
    RemediationSafety,
    ScanReport,
    Severity,
)

#: What each confidence class establishes, in one sentence.
_CLAIMS: Final[dict[ConfidenceType, str]] = {
    ConfidenceType.DETERMINISTIC: "The stated trace was observed exactly in these bytes.",
    ConfidenceType.VERIFIED: (
        "A cryptographic or provider mechanism was run and returned this result."
    ),
    ConfidenceType.PROBABILISTIC: "A calibrated estimate placed this artifact in this range.",
    ConfidenceType.HEURISTIC: "A rule of thumb matched.",
}

#: What it does not establish. The sentence an interface drops first.
_LIMITS: Final[dict[ConfidenceType, str]] = {
    ConfidenceType.DETERMINISTIC: (
        "It does not establish that the artifact was generated by AI, only that this trace "
        "is present."
    ),
    ConfidenceType.VERIFIED: (
        "It establishes what the mechanism checked and nothing beyond that mechanism's scope."
    ),
    ConfidenceType.PROBABILISTIC: (
        "It is a measurement, not provenance, and it identifies no author."
    ),
    ConfidenceType.HEURISTIC: (
        "It is a prompt for human review. It is not evidence of authorship and must not be "
        "reported as provenance."
    ),
}

_PROVENANCE_LIMITS: Final[dict[ProvenanceClass, str]] = {
    ProvenanceClass.ATTRIBUTION: (
        "An attribution string is text someone wrote. Anyone can write it, and its absence "
        "means nothing."
    ),
    ProvenanceClass.METADATA: "Metadata is editable by anyone who can open the file.",
    ProvenanceClass.PROVENANCE_METADATA: (
        "This provenance metadata is unverified: it was read, not checked."
    ),
    ProvenanceClass.AUTHENTICATED_PROVENANCE: (
        "Authenticated provenance is only as strong as the trust anchors configured for the scan."
    ),
    ProvenanceClass.PROVIDER_WATERMARK: (
        "A provider marker was observed. Observing a marker is not verifying it."
    ),
    ProvenanceClass.HEURISTIC: "A style signal is never provenance.",
}

_LSP_SEVERITY: Final[dict[Severity, int]] = {
    Severity.CRITICAL: 1,
    Severity.HIGH: 1,
    Severity.MEDIUM: 2,
    Severity.LOW: 3,
    Severity.INFO: 4,
}

#: Cleanup that changes bytes a reader can see, as opposed to metadata.
_VISIBLE_CHANGE: Final[frozenset[RemediationSafety]] = frozenset(
    {RemediationSafety.PREDICTABLE_CONTENT, RemediationSafety.DESTRUCTIVE}
)


@dataclass(frozen=True, slots=True)
class FindingExplanation:
    """One finding, stated with its limits attached."""

    finding_id: str
    title: str
    artifact_path: str
    severity: str
    category: str
    detector_id: str
    claims: str
    #: The sentence an interface must actively discard rather than never have.
    does_not_claim: tuple[str, ...]
    evidence_summary: str
    removable: bool
    #: Line and column when the detector reported them; ``None`` otherwise. An
    #: interface that needs a caret cannot invent one from a byte offset.
    line: int | None = None
    column: int | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "finding_id": self.finding_id,
            "title": self.title,
            "artifact_path": self.artifact_path,
            "severity": self.severity,
            "category": self.category,
            "detector_id": self.detector_id,
            "claims": self.claims,
            "does_not_claim": list(self.does_not_claim),
            "evidence_summary": self.evidence_summary,
            "removable": self.removable,
            "line": self.line,
            "column": self.column,
        }


@dataclass(frozen=True, slots=True)
class RemediationStep:
    """One planned operation, described before it happens."""

    remediation_id: str
    artifact_path: str
    description: str
    safety: str
    finding_ids: tuple[str, ...]
    #: Whether applying this would change bytes a reader can see, as opposed to
    #: metadata. The distinction decides whether a person must look at the result.
    changes_visible_content: bool
    requires_explicit_opt_in: bool

    def to_dict(self) -> dict[str, Any]:
        return {
            "remediation_id": self.remediation_id,
            "artifact_path": self.artifact_path,
            "description": self.description,
            "safety": self.safety,
            "finding_ids": list(self.finding_ids),
            "changes_visible_content": self.changes_visible_content,
            "requires_explicit_opt_in": self.requires_explicit_opt_in,
        }


@dataclass(frozen=True, slots=True)
class RemediationPreview:
    """What a plan would do, and everything it deliberately would not."""

    policy: str
    steps: tuple[RemediationStep, ...] = ()
    #: Findings a person must decide about. Not a failure; a handoff.
    needs_review: tuple[str, ...] = ()
    #: Findings preserved on purpose — provenance evidence is not litter.
    preserved: tuple[str, ...] = ()
    #: Findings automatic cleanup refused to touch.
    blocked: tuple[str, ...] = ()

    @property
    def changes_visible_content(self) -> bool:
        return any(step.changes_visible_content for step in self.steps)

    def to_dict(self) -> dict[str, Any]:
        return {
            "policy": self.policy,
            "steps": [step.to_dict() for step in self.steps],
            "needs_review": list(self.needs_review),
            "preserved": list(self.preserved),
            "blocked": list(self.blocked),
            "changes_visible_content": self.changes_visible_content,
        }


@dataclass(frozen=True, slots=True)
class IntegrityEvidence:
    """What can be shown to someone asking whether cleanup changed the content."""

    status: str
    explanation: str
    verified: bool
    before_sha256: str | None = None
    after_sha256: str | None = None
    logical_before_sha256: str | None = None
    logical_after_sha256: str | None = None
    intentionally_removed: tuple[str, ...] = ()

    @property
    def visible_content_unchanged(self) -> bool | None:
        """Whether the visible content is provably the same, or ``None`` if unknown.

        ``None`` rather than ``False`` when the logical digests are missing: a
        check that did not run is not a check that failed, and an interface that
        collapsed the two would report an unverifiable artifact as a damaged one.
        """

        if self.logical_before_sha256 is None or self.logical_after_sha256 is None:
            return None
        return self.logical_before_sha256 == self.logical_after_sha256

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "explanation": self.explanation,
            "verified": self.verified,
            "before_sha256": self.before_sha256,
            "after_sha256": self.after_sha256,
            "logical_before_sha256": self.logical_before_sha256,
            "logical_after_sha256": self.logical_after_sha256,
            "intentionally_removed": list(self.intentionally_removed),
            "visible_content_unchanged": self.visible_content_unchanged,
        }


@dataclass(frozen=True, slots=True)
class CertificateView:
    """An audit certificate as something to display, limits included."""

    certificate_id: str
    subject: str
    issued_at: str
    expires_at: str | None
    scanner: str
    #: Whether the scan behind the certificate ran to completion. A certificate
    #: over an incomplete scan attests to less than it looks like it does.
    scan_complete: bool = True
    #: Every check, so a green tick cannot stand in for four of them.
    checks: dict[str, bool | None] = field(default_factory=dict)
    #: "Nothing that was checked came back false." Not "everything was checked":
    #: an unsigned certificate nobody compared to a file is `valid` and says
    #: almost nothing, which is why the two fields below exist beside it.
    valid: bool = False
    #: The issuer was authenticated and the artifact bytes matched. The predicate
    #: a reader means by "this checks out", and the one a badge should use.
    authenticated: bool = False
    #: What nobody looked at, one clause each, so a surface rendering this cannot
    #: reproduce the mistake of putting `valid` under a green tick on its own.
    unchecked: tuple[str, ...] = ()
    explanations: tuple[str, ...] = ()

    #: What a TrueAI certificate never asserts, restated wherever one is shown.
    attests_only: str = (
        "A named scanner version and detector scope found no scoped indicators in exact "
        "artifact bytes at a recorded time. It does not certify human authorship and does "
        "not certify that AI was never used."
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "certificate_id": self.certificate_id,
            "subject": self.subject,
            "issued_at": self.issued_at,
            "expires_at": self.expires_at,
            "scanner": self.scanner,
            "scan_complete": self.scan_complete,
            "checks": dict(self.checks),
            "valid": self.valid,
            "authenticated": self.authenticated,
            "unchecked": list(self.unchecked),
            "explanations": list(self.explanations),
            "attests_only": self.attests_only,
        }


# -- projection ------------------------------------------------------------------------


def explain_finding(finding: Finding) -> FindingExplanation:
    """Describe one finding with the limits its evidence class implies."""

    limits = [_LIMITS[finding.confidence_type]]
    provenance_limit = _PROVENANCE_LIMITS.get(finding.provenance_class)
    if provenance_limit is not None:
        limits.append(provenance_limit)
    location = finding.location
    return FindingExplanation(
        finding_id=finding.id,
        title=finding.title,
        artifact_path=finding.artifact_path,
        severity=finding.severity.value,
        category=finding.category.value,
        detector_id=finding.detector_id,
        claims=_CLAIMS[finding.confidence_type],
        does_not_claim=tuple(limits),
        evidence_summary=finding.description,
        removable=finding.removable,
        line=location.line if location else None,
        column=location.column if location else None,
    )


def explain_findings(report: ScanReport) -> tuple[FindingExplanation, ...]:
    """Describe every finding in a report, in report order."""

    return tuple(explain_finding(finding) for finding in report.findings)


def _step(remediation: Remediation) -> RemediationStep:
    return RemediationStep(
        remediation_id=remediation.remediation_id,
        artifact_path=remediation.artifact_path,
        description=remediation.description,
        safety=remediation.safety.value,
        finding_ids=tuple(remediation.finding_ids),
        changes_visible_content=remediation.safety in _VISIBLE_CHANGE,
        requires_explicit_opt_in=remediation.safety is RemediationSafety.DESTRUCTIVE,
    )


def remediation_preview(plan: RemediationPlan) -> RemediationPreview:
    """Describe what a plan would do before anything is applied."""

    return RemediationPreview(
        policy=plan.policy,
        steps=tuple(_step(item) for item in plan.remediations),
        needs_review=tuple(plan.review_findings),
        preserved=tuple(plan.preserved_findings),
        blocked=tuple(plan.blocked_findings),
    )


def integrity_evidence(integrity: IntegrityReport) -> IntegrityEvidence:
    """Describe what can be shown about whether content survived cleanup."""

    return IntegrityEvidence(
        status=integrity.status.value,
        explanation=integrity.explanation,
        verified=integrity.status is IntegrityStatus.PASS,
        before_sha256=integrity.before_sha256,
        after_sha256=integrity.after_sha256,
        logical_before_sha256=integrity.logical_before_sha256,
        logical_after_sha256=integrity.logical_after_sha256,
        intentionally_removed=tuple(integrity.intentionally_removed),
    )


def certificate_view(
    certificate: AuditCertificate,
    verification: CertificateVerification | None = None,
) -> CertificateView:
    """Describe a certificate and, when checked, every check separately.

    Separately because a single green tick over identity, signature, artifact
    binding, validity period, and revocation would let four unknowns hide behind
    one answer.
    """

    checks: dict[str, bool | None] = {}
    explanations: tuple[str, ...] = ()
    valid = False
    authenticated = False
    unchecked: tuple[str, ...] = ()
    if verification is not None:
        checks = {
            "identity_matches_contents": verification.certificate_id_valid,
            "signature_present": verification.signature_present,
            "signature_verified": verification.signature_verified,
            "artifact_matches": verification.artifact_verified,
            "within_validity_period": verification.temporal_valid,
            "revocation_checked": verification.revocation_checked,
            "revoked": verification.revoked,
        }
        explanations = tuple(verification.explanations)
        valid = verification.valid
        authenticated = verification.authenticated
        unchecked = verification.unchecked()
    return CertificateView(
        certificate_id=certificate.certificate_id,
        subject=certificate.artifact.path,
        issued_at=certificate.issued_at.isoformat(),
        expires_at=certificate.expires_at.isoformat() if certificate.expires_at else None,
        scanner=f"trueai-core {certificate.package_version}",
        scan_complete=certificate.scan_complete,
        checks=checks,
        valid=valid,
        authenticated=authenticated,
        unchecked=unchecked,
        explanations=explanations,
    )


def lsp_severity(severity: Severity) -> int:
    """Map a TrueAI severity onto the Language Server Protocol's four levels."""

    return _LSP_SEVERITY[severity]


__all__ = [
    "CertificateView",
    "FindingExplanation",
    "IntegrityEvidence",
    "RemediationPreview",
    "RemediationStep",
    "certificate_view",
    "explain_finding",
    "explain_findings",
    "integrity_evidence",
    "lsp_severity",
    "remediation_preview",
]
