"""Research-side governance: the rules a corpus must satisfy before it exists.

Kept out of the scanning path entirely. Nothing here is imported by a detector,
a cleaner, or the engine, and nothing here changes what a scan reports — it
governs data collection, which is a separate activity with separate obligations.
"""

from trueai.research.corpus import (
    AdmissionDecision,
    ConsentRecord,
    ConsentStatus,
    ContaminationControl,
    CorpusAudit,
    CorpusError,
    CorpusManifest,
    CorpusPolicy,
    CorpusSample,
    DomainBalance,
    LicenseTerms,
    LicenseUse,
    RetentionRule,
    Split,
    admit,
    admit_all,
    audit_corpus,
    withdraw_consent,
)
from trueai.research.evaluation import (
    CalibrationBin,
    CalibrationResult,
    EvaluationError,
    EvaluationResult,
    GroupResult,
    Prediction,
    ProtocolRecord,
    RateEstimate,
    calibration,
    evaluate,
)
from trueai.research.features import (
    FEATURE_SET_VERSION,
    FeatureError,
    FeatureSet,
    FeatureVector,
    ModelCard,
    ModelScore,
    ScoreModel,
    build_vector,
    score_with,
    try_score,
)

__all__ = [
    "FEATURE_SET_VERSION",
    "AdmissionDecision",
    "CalibrationBin",
    "CalibrationResult",
    "ConsentRecord",
    "ConsentStatus",
    "ContaminationControl",
    "CorpusAudit",
    "CorpusError",
    "CorpusManifest",
    "CorpusPolicy",
    "CorpusSample",
    "DomainBalance",
    "EvaluationError",
    "EvaluationResult",
    "FeatureError",
    "FeatureSet",
    "FeatureVector",
    "GroupResult",
    "LicenseTerms",
    "LicenseUse",
    "ModelCard",
    "ModelScore",
    "Prediction",
    "ProtocolRecord",
    "RateEstimate",
    "RetentionRule",
    "ScoreModel",
    "Split",
    "admit",
    "admit_all",
    "audit_corpus",
    "build_vector",
    "calibration",
    "evaluate",
    "score_with",
    "try_score",
    "withdraw_consent",
]
