"""Research-side governance: the rules a corpus must satisfy before it exists.

Kept out of the scanning path entirely. Nothing here is imported by a detector,
a cleaner, or the engine, and nothing here changes what a scan reports — it
governs data collection, which is a separate activity with separate obligations.
"""

from trueai.research.corpus import (
    AdmissionDecision,
    ConsentRecord,
    ConsentStatus,
    ContaminationControl,
    CorpusAudit,
    CorpusError,
    CorpusManifest,
    CorpusPolicy,
    CorpusSample,
    DomainBalance,
    LicenseTerms,
    LicenseUse,
    RetentionRule,
    Split,
    admit,
    admit_all,
    audit_corpus,
    withdraw_consent,
)
from trueai.research.evaluation import (
    CalibrationBin,
    CalibrationResult,
    EvaluationError,
    EvaluationResult,
    GroupResult,
    Prediction,
    ProtocolRecord,
    RateEstimate,
    calibration,
    evaluate,
)
from trueai.research.features import (
    FEATURE_SET_VERSION,
    FeatureError,
    FeatureSet,
    FeatureVector,
    ModelCard,
    ModelScore,
    ScoreModel,
    build_vector,
    score_with,
    try_score,
)
from trueai.research.longitudinal import (
    ALTERNATIVE_EXPLANATIONS,
    BaselineDocument,
    LongitudinalError,
    ShiftBand,
    StyleBaseline,
    StyleComparison,
    compare,
)
from trueai.research.release import (
    DatasetStatement,
    ModelFile,
    ModelManifest,
    OperatingPoint,
    RegressionVerdict,
    ReleaseDecision,
    ReleaseError,
    ThresholdSet,
    build_manifest,
    check_regression,
    compute_manifest_id,
    may_expose,
    sign_manifest,
    verify_manifest,
)

__all__ = [
    "ALTERNATIVE_EXPLANATIONS",
    "FEATURE_SET_VERSION",
    "AdmissionDecision",
    "BaselineDocument",
    "CalibrationBin",
    "CalibrationResult",
    "ConsentRecord",
    "ConsentStatus",
    "ContaminationControl",
    "CorpusAudit",
    "CorpusError",
    "CorpusManifest",
    "CorpusPolicy",
    "CorpusSample",
    "DatasetStatement",
    "DomainBalance",
    "EvaluationError",
    "EvaluationResult",
    "FeatureError",
    "FeatureSet",
    "FeatureVector",
    "GroupResult",
    "LicenseTerms",
    "LicenseUse",
    "LongitudinalError",
    "ModelCard",
    "ModelFile",
    "ModelManifest",
    "ModelScore",
    "OperatingPoint",
    "Prediction",
    "ProtocolRecord",
    "RateEstimate",
    "RegressionVerdict",
    "ReleaseDecision",
    "ReleaseError",
    "RetentionRule",
    "ScoreModel",
    "ShiftBand",
    "Split",
    "StyleBaseline",
    "StyleComparison",
    "ThresholdSet",
    "admit",
    "admit_all",
    "audit_corpus",
    "build_manifest",
    "build_vector",
    "calibration",
    "check_regression",
    "compare",
    "compute_manifest_id",
    "evaluate",
    "may_expose",
    "score_with",
    "sign_manifest",
    "try_score",
    "verify_manifest",
    "withdraw_consent",
]
