from pathlib import Path

from trueai import TrueAIEngine
from trueai.core.models import FindingCategory


def test_explicit_provider_attribution_is_literal_and_remediable() -> None:
    report = TrueAIEngine.default().scan_text(
        "Release notes\nGenerated with ChatGPT\nhttps://claude.ai/share/session_1\n"
    )
    findings = [
        item for item in report.findings if item.category == FindingCategory.EXPLICIT_AI_ATTRIBUTION
    ]

    assert {item.provider for item in findings} == {"openai", "anthropic"}
    assert all(item.confidence_type.value == "deterministic" for item in findings)
    assert all(item.removable for item in findings)


def test_generic_build_generator_language_is_not_false_positive() -> None:
    report = TrueAIEngine.default().scan_text(
        "This file was generated by the protobuf compiler. Do not edit manually."
    )

    assert not [
        item for item in report.findings if item.category == FindingCategory.EXPLICIT_AI_ATTRIBUTION
    ]


def test_negative_ai_authorship_statement_is_not_attribution() -> None:
    report = TrueAIEngine.default().scan_text(
        "TrueAI reports evidence and does not label content as AI-generated."
    )

    assert not [
        item for item in report.findings if item.category == FindingCategory.EXPLICIT_AI_ATTRIBUTION
    ]


def test_python_attribution_is_restricted_to_comments(tmp_path: Path) -> None:
    source = tmp_path / "example.py"
    source.write_text(
        'literal = "Generated with ChatGPT"\n# Generated with Claude\n',
        encoding="utf-8",
    )

    report = TrueAIEngine.default().scan(source)
    generated_comments = [
        finding
        for finding in report.findings
        if finding.category == FindingCategory.GENERATED_COMMENT
    ]

    assert len(generated_comments) == 1
    assert generated_comments[0].provider == "anthropic"


def test_unparsed_javascript_comment_candidate_is_review_only(tmp_path: Path) -> None:
    source = tmp_path / "example.js"
    source.write_text(
        'const label = "// Generated with ChatGPT";\n',
        encoding="utf-8",
    )

    report = TrueAIEngine.default().scan(source)
    finding = next(
        item for item in report.findings if item.category == FindingCategory.GENERATED_COMMENT
    )

    assert finding.confidence_type.value == "heuristic"
    assert finding.removable is False
    assert finding.remediation_id is None
    assert "review-only" in finding.tags


def test_attribution_inside_substantive_text_is_not_auto_removable() -> None:
    report = TrueAIEngine.default().scan_text(
        "The release was Generated with ChatGPT and then independently verified.\n"
    )
    finding = next(
        item for item in report.findings if item.category == FindingCategory.EXPLICIT_AI_ATTRIBUTION
    )

    assert finding.removable is False
    assert finding.remediation_id is None
    assert "requires review" in finding.description


def test_substantive_python_comment_is_not_auto_removable(tmp_path: Path) -> None:
    source = tmp_path / "review.py"
    source.write_text(
        "# Parser generated with ChatGPT, then corrected for escaped input\n",
        encoding="utf-8",
    )

    report = TrueAIEngine.default().scan(source)
    finding = next(
        item for item in report.findings if item.category == FindingCategory.GENERATED_COMMENT
    )

    assert finding.removable is False
    assert finding.remediation_id is None
    assert "review-only" in finding.tags
