"""One projection, three surfaces, and the sentence none of them may drop.

Two things are being tested. First, that every adapter carries what a finding
does *not* establish — the sentence a short format loses first and the one the
whole project turns on. Second, that each output format's own metacharacters are
escaped: a workflow annotation is a control stream, a Markdown table is
structure, and both are built from strings that came out of the artifact.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any

import pytest
from typer.testing import CliRunner

from trueai.adapters import (
    BUNDLE_VERSION,
    certificate_view,
    desktop_bundle,
    diagnostics_by_file,
    explain_finding,
    explain_findings,
    hover,
    integrity_evidence,
    job_summary,
    lsp_severity,
    publish_payloads,
    remediation_preview,
    workflow_annotations,
)
from trueai.cli.app import app
from trueai.core.models import (
    ArtifactDescriptor,
    ArtifactType,
    ConfidenceType,
    EvidenceType,
    Finding,
    FindingCategory,
    FindingLocation,
    IntegrityReport,
    IntegrityStatus,
    ProvenanceClass,
    Remediation,
    RemediationPlan,
    RemediationSafety,
    ScanDiagnostic,
    ScanReport,
    ScanSummary,
    Severity,
)

runner = CliRunner()

NOW = datetime(2026, 8, 25, 12, 0, tzinfo=UTC)


def finding(**extra: Any) -> Finding:
    fields: dict[str, Any] = {
        "id": "finding-000000000001",
        "detector_id": "example.detector.v1",
        "category": FindingCategory.EXPLICIT_AI_ATTRIBUTION,
        "artifact_path": "notes.md",
        "confidence": 1.0,
        "confidence_type": ConfidenceType.DETERMINISTIC,
        "severity": Severity.HIGH,
        "evidence_type": EvidenceType.TEXT,
        "title": "Attribution string",
        "description": "The document says it was generated with a tool.",
        "provenance_class": ProvenanceClass.ATTRIBUTION,
    }
    fields.update(extra)
    return Finding.model_validate(fields)


def report(**extra: Any) -> ScanReport:
    descriptor = ArtifactDescriptor(
        path="notes.md", artifact_type=ArtifactType.MARKDOWN, size=42, sha256="0" * 64
    )
    findings = extra.pop("findings", (finding(),))
    fields: dict[str, Any] = {
        "artifact": descriptor,
        "artifacts": (descriptor,),
        "summary": ScanSummary(artifact_count=1, finding_count=len(findings)),
        "findings": findings,
        "integrity": IntegrityReport(
            status=IntegrityStatus.NOT_MODIFIED, explanation="Scan-only operation."
        ),
    }
    fields.update(extra)
    return ScanReport.model_validate(fields)


# -- the sentence that must survive every format -------------------------------------


def test_a_deterministic_finding_states_what_it_does_not_establish() -> None:
    explanation = explain_finding(finding())

    assert "observed exactly" in explanation.claims
    assert any(
        "does not establish that the artifact was generated by AI" in item
        for item in explanation.does_not_claim
    )


def test_an_attribution_finding_says_anyone_could_have_written_it() -> None:
    explanation = explain_finding(finding(provenance_class=ProvenanceClass.ATTRIBUTION))

    assert any("Anyone can write it" in item for item in explanation.does_not_claim)


def test_a_heuristic_finding_is_never_described_as_evidence_of_authorship() -> None:
    explanation = explain_finding(
        finding(
            confidence_type=ConfidenceType.HEURISTIC,
            confidence=0.6,
            provenance_class=ProvenanceClass.HEURISTIC,
        )
    )

    joined = " ".join(explanation.does_not_claim)
    assert "not evidence of authorship" in joined
    assert "never provenance" in joined


def test_every_confidence_class_has_a_limit_sentence() -> None:
    """A class added without one would ship a claim with nothing qualifying it."""

    for confidence in ConfidenceType:
        explanation = explain_finding(finding(confidence_type=confidence, confidence=0.5))
        assert explanation.claims
        assert explanation.does_not_claim


@pytest.mark.parametrize("provenance", list(ProvenanceClass))
def test_every_provenance_class_is_accounted_for(provenance: ProvenanceClass) -> None:
    explanation = explain_finding(finding(provenance_class=provenance))

    assert explanation.does_not_claim


def test_a_location_is_carried_only_when_the_detector_reported_one() -> None:
    """An interface cannot invent a caret from a byte offset."""

    with_line = explain_finding(finding(location=FindingLocation(line=4, column=9)))
    offset_only = explain_finding(finding(location=FindingLocation(offset=120)))

    assert (with_line.line, with_line.column) == (4, 9)
    assert (offset_only.line, offset_only.column) == (None, None)


# -- CI: a control stream built from hostile strings ---------------------------------


def test_an_annotation_carries_the_limit_next_to_the_claim() -> None:
    """A CI line reading "AI attribution found" is the one that gets screenshotted."""

    line = workflow_annotations(report())[0]

    assert "does not establish that the artifact was generated by AI" in line


def test_a_newline_in_a_description_cannot_forge_a_second_command() -> None:
    """The injection that matters: a message is one line of a control stream.

    ``::error::`` surviving as *text* is harmless — a runner splits commands on
    real newlines, so the property is that no newline remains, not that the
    characters are gone.
    """

    hostile = finding(description="clean\n::error::the build is fine")

    annotations = workflow_annotations(report(findings=(hostile,)))

    assert len(annotations) == 1
    assert "\n" not in annotations[0]
    assert "\r" not in annotations[0]
    assert "%0A" in annotations[0]


def test_a_percent_is_escaped_so_an_escape_cannot_be_forged() -> None:
    hostile = finding(description="100%0Anot really a newline")

    line = workflow_annotations(report(findings=(hostile,)))[0]

    assert "%250A" in line


def test_a_comma_in_a_path_cannot_add_an_annotation_property() -> None:
    """A comma separates properties, so an unescaped one in a path invents them."""

    hostile = finding(artifact_path="a,line=99,col=1")

    line = workflow_annotations(report(findings=(hostile,)))[0]
    properties = line.split("::", 2)[1].split(" ", 1)[1].split(",")

    assert [item.split("=", 1)[0] for item in properties] == ["file", "title"]
    assert "%2C" in line


def test_severity_decides_error_or_warning_and_info_is_never_an_error() -> None:
    """A job that failed on every INFO finding would be switched off in a week."""

    high = workflow_annotations(report(findings=(finding(severity=Severity.HIGH),)))[0]
    info = workflow_annotations(report(findings=(finding(severity=Severity.INFO),)))[0]

    assert high.startswith("::error ")
    assert info.startswith("::warning ")


def test_a_line_and_column_reach_the_annotation_when_known() -> None:
    line = workflow_annotations(
        report(findings=(finding(location=FindingLocation(line=7, column=3)),))
    )[0]

    assert "line=7" in line
    assert "col=3" in line


def test_no_line_property_is_invented_when_none_was_reported() -> None:
    line = workflow_annotations(report(findings=(finding(location=None),)))[0]

    assert "line=" not in line


# -- CI: a summary built from the same strings ---------------------------------------


def test_a_pipe_in_a_value_cannot_rewrite_the_table_around_it() -> None:
    summary = job_summary(report(findings=(finding(title="a | b | c"),)))

    header_columns = summary.splitlines()[4].count("|")
    row = next(line for line in summary.splitlines() if "a \\| b" in line)

    assert row.count("|") - row.count("\\|") == header_columns


def test_the_summary_states_the_limit_in_its_own_column() -> None:
    summary = job_summary(report())

    assert "Does not claim" in summary
    assert "does not claim the artifact was generated by AI" in summary


def test_the_summary_reports_coverage_before_it_reports_nothing_found() -> None:
    summary = job_summary(
        report(
            findings=(),
            diagnostics=(
                ScanDiagnostic(
                    code="artifact_too_large",
                    message="Skipped a 40 MB file.",
                    severity=Severity.HIGH,
                ),
            ),
        )
    )

    assert "### Coverage" in summary
    assert summary.index("### Coverage") < summary.index("### Integrity")


def test_the_summary_warns_when_cleanup_would_change_visible_content() -> None:
    plan = RemediationPlan(
        policy="client-delivery",
        remediations=(
            Remediation(
                id="rem-1",
                remediation_id="strip.comment",
                artifact_path="notes.md",
                finding_ids=("finding-000000000001",),
                description="Remove a generated comment.",
                safety=RemediationSafety.PREDICTABLE_CONTENT,
            ),
        ),
    )

    summary = job_summary(report(), plan)

    assert "would change visible content" in summary


# -- IDE ------------------------------------------------------------------------------


def test_diagnostics_are_keyed_by_file() -> None:
    grouped = diagnostics_by_file(report())

    assert set(grouped) == {"notes.md"}
    assert len(grouped["notes.md"]) == 1


def test_a_clean_file_still_appears_so_stale_markers_can_be_cleared() -> None:
    """Otherwise yesterday's squiggles stay under text that no longer has a problem."""

    grouped = diagnostics_by_file(report(findings=()))

    assert grouped == {"notes.md": []}


def test_a_range_is_zero_based_because_lsp_counts_from_zero() -> None:
    grouped = diagnostics_by_file(
        report(findings=(finding(location=FindingLocation(line=7, column=3)),))
    )

    assert grouped["notes.md"][0]["range"]["start"] == {"line": 6, "character": 2}


def test_a_missing_range_is_admitted_rather_than_guessed() -> None:
    """A squiggle under the wrong text is worse than none: it looks authoritative."""

    grouped = diagnostics_by_file(report(findings=(finding(location=FindingLocation(offset=99)),)))
    diagnostic = grouped["notes.md"][0]

    assert diagnostic["range"]["start"] == {"line": 0, "character": 0}
    assert "no line information" in diagnostic["message"]


def test_severity_is_mapped_onto_the_four_levels_lsp_has() -> None:
    assert lsp_severity(Severity.CRITICAL) == lsp_severity(Severity.HIGH) == 1
    assert lsp_severity(Severity.MEDIUM) == 2
    assert lsp_severity(Severity.LOW) == 3
    assert lsp_severity(Severity.INFO) == 4


def test_an_info_finding_never_becomes_an_editor_error() -> None:
    grouped = diagnostics_by_file(report(findings=(finding(severity=Severity.INFO),)))

    assert grouped["notes.md"][0]["severity"] == 4


def test_a_diagnostic_carries_the_limit_and_the_evidence_class() -> None:
    diagnostic = diagnostics_by_file(report())["notes.md"][0]

    assert "does not establish" in diagnostic["message"]
    assert diagnostic["data"]["confidence_type"] == "deterministic"
    assert diagnostic["data"]["provenance_class"] == "attribution"
    assert diagnostic["source"] == "trueai"


def test_publish_payloads_are_one_message_per_file() -> None:
    payloads = publish_payloads(report(), root="file:///work")

    assert payloads[0]["uri"] == "file:///work/notes.md"
    assert len(payloads[0]["diagnostics"]) == 1


def test_hover_returns_markdown_with_the_limits_spelled_out() -> None:
    content = hover(report(), "finding-000000000001")

    assert content is not None
    assert content["contents"]["kind"] == "markdown"
    assert "**Does not claim:**" in content["contents"]["value"]


def test_hover_on_an_unknown_finding_returns_nothing() -> None:
    assert hover(report(), "finding-000000000404") is None


# -- desktop --------------------------------------------------------------------------


def test_the_bundle_declares_a_version_a_client_can_refuse() -> None:
    bundle = desktop_bundle(report())

    assert bundle["bundle_version"] == BUNDLE_VERSION


def test_the_bundle_is_json_serializable() -> None:
    """It is a wire format; anything unserializable is a runtime failure later."""

    json.dumps(desktop_bundle(report()))


def test_the_bundle_carries_coverage_beside_the_findings() -> None:
    """A client rendering findings alone shows a clean page for a half-read scan."""

    bundle = desktop_bundle(
        report(
            diagnostics=(
                ScanDiagnostic(
                    code="artifact_too_large", message="Skipped.", severity=Severity.HIGH
                ),
            )
        )
    )

    assert bundle["coverage"][0]["code"] == "artifact_too_large"


def test_the_bundle_carries_the_limits_with_every_finding() -> None:
    bundle = desktop_bundle(report())

    assert bundle["findings"][0]["does_not_claim"]


def test_remediation_and_certificate_are_absent_rather_than_empty() -> None:
    """A client can tell "no plan was made" from "a plan with nothing in it"."""

    bundle = desktop_bundle(report())

    assert bundle["remediation"] is None
    assert bundle["certificate"] is None


# -- remediation and integrity views -------------------------------------------------


def test_a_preview_separates_what_will_change_from_what_will_not() -> None:
    plan = RemediationPlan(
        policy="client-delivery",
        remediations=(
            Remediation(
                id="rem-1",
                remediation_id="strip.metadata",
                artifact_path="notes.md",
                finding_ids=("finding-000000000001",),
                description="Remove generator metadata.",
                safety=RemediationSafety.SAFE_METADATA,
            ),
        ),
        review_findings=("finding-000000000002",),
        preserved_findings=("finding-000000000003",),
        blocked_findings=("finding-000000000004",),
    )

    preview = remediation_preview(plan)

    assert not preview.changes_visible_content
    assert preview.needs_review == ("finding-000000000002",)
    assert preview.preserved == ("finding-000000000003",)
    assert preview.blocked == ("finding-000000000004",)


def test_a_destructive_step_is_marked_as_needing_explicit_consent() -> None:
    plan = RemediationPlan(
        policy="deep-clean",
        remediations=(
            Remediation(
                id="rem-1",
                remediation_id="rewrite.history",
                artifact_path="repo",
                finding_ids=(),
                description="Rewrite commit history.",
                safety=RemediationSafety.DESTRUCTIVE,
            ),
        ),
    )

    step = remediation_preview(plan).steps[0]

    assert step.requires_explicit_opt_in
    assert step.changes_visible_content


def test_an_unverifiable_integrity_result_is_unknown_not_false() -> None:
    """A check that did not run is not a check that failed."""

    evidence = integrity_evidence(
        IntegrityReport(status=IntegrityStatus.NOT_VERIFIABLE, explanation="No logical digest.")
    )

    assert evidence.visible_content_unchanged is None
    assert not evidence.verified


def test_matching_logical_digests_prove_the_visible_content_survived() -> None:
    evidence = integrity_evidence(
        IntegrityReport(
            status=IntegrityStatus.PASS,
            explanation="Metadata only.",
            logical_before_sha256="a" * 64,
            logical_after_sha256="a" * 64,
        )
    )

    assert evidence.visible_content_unchanged is True
    assert evidence.verified


def test_differing_logical_digests_report_a_visible_change() -> None:
    evidence = integrity_evidence(
        IntegrityReport(
            status=IntegrityStatus.FAIL,
            explanation="Content changed.",
            logical_before_sha256="a" * 64,
            logical_after_sha256="b" * 64,
        )
    )

    assert evidence.visible_content_unchanged is False


# -- certificate view -----------------------------------------------------------------


def test_a_certificate_view_restates_what_a_certificate_never_asserts() -> None:
    pytest.importorskip("cryptography", reason="Signing needs the attestation extra")

    from trueai.core.certificates import issue_certificate
    from trueai.core.models import ScanOptions

    certificate = issue_certificate(report(findings=()), ScanOptions(), issued_at=NOW)

    view = certificate_view(certificate)

    assert "does not certify human authorship" in view.attests_only
    assert "does not certify that AI was never used" in view.attests_only


def test_every_check_is_shown_separately_rather_than_as_one_tick() -> None:
    """Four unknowns must not hide behind a single green answer."""

    pytest.importorskip("cryptography", reason="Signing needs the attestation extra")

    from trueai.core.certificates import CertificateVerification, issue_certificate
    from trueai.core.models import ScanOptions

    certificate = issue_certificate(report(findings=()), ScanOptions(), issued_at=NOW)
    verification = CertificateVerification(
        valid=False,
        certificate_id_valid=True,
        signature_present=False,
        signature_verified=None,
        artifact_verified=True,
        explanations=("the certificate is unsigned",),
    )

    view = certificate_view(certificate, verification)

    assert view.checks["identity_matches_contents"] is True
    assert view.checks["signature_present"] is False
    assert view.checks["signature_verified"] is None
    assert not view.valid


# -- through the command line ---------------------------------------------------------


def test_the_cli_emits_ci_annotations_and_a_summary(tmp_path) -> None:
    target = tmp_path / "note.md"
    target.write_text("Generated with ChatGPT\n", encoding="utf-8")

    result = runner.invoke(app, ["scan", str(target), "-f", "ci"])

    assert "::error " in result.output or "::warning " in result.output
    assert "## TrueAI scan" in result.output


def test_the_cli_emits_editor_diagnostics(tmp_path) -> None:
    target = tmp_path / "note.md"
    target.write_text("Generated with ChatGPT\n", encoding="utf-8")

    result = runner.invoke(app, ["scan", str(target), "-f", "ide"])
    payload = json.loads(result.output)

    assert "note.md" in payload
    assert payload["note.md"][0]["source"] == "trueai"


def test_the_cli_emits_a_desktop_bundle(tmp_path) -> None:
    target = tmp_path / "note.md"
    target.write_text("Generated with ChatGPT\n", encoding="utf-8")

    result = runner.invoke(app, ["scan", str(target), "-f", "desktop"])
    payload = json.loads(result.output)

    assert payload["bundle_version"] == BUNDLE_VERSION
    assert payload["findings"][0]["does_not_claim"]


# -- the adapters add nothing the report does not already imply ----------------------


def test_every_explanation_maps_back_to_a_finding_in_the_report() -> None:
    subject = report(
        findings=(finding(), finding(id="finding-000000000002", artifact_path="other.md"))
    )

    explanations = explain_findings(subject)

    assert [item.finding_id for item in explanations] == [item.id for item in subject.findings]
