"""Which file a finding is in, in the report a person actually reads.

The terminal printed the artifact path only when the finding carried a line
number. Most findings do not: a container box, a document property, an editor
namespace, a generator comment in an XML document are about a whole file. So a
scan over a directory printed

    LOW SVG generator comment

with nothing saying which of the files it came from, while the JSON and SARIF
renderings of the same finding both carried the path all along. Somebody
triaging a hundred-file delivery could read the finding and not know where to
look.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from trueai.cli.app import app

runner = CliRunner()

SVG_WITH_A_GENERATOR_COMMENT = (
    '<svg xmlns="http://www.w3.org/2000/svg" width="4" height="4">'
    "<!-- Created with Figma -->"
    '<rect width="4" height="4"/>'
    "</svg>"
)

SOURCE_WITH_A_LINE = "def solve(n):\n    # Generated by ChatGPT\n    return n\n"


@pytest.fixture
def workspace(tmp_path: Path) -> Path:
    (tmp_path / "logo.svg").write_text(SVG_WITH_A_GENERATOR_COMMENT, encoding="utf-8")
    (tmp_path / "solver.py").write_text(SOURCE_WITH_A_LINE, encoding="utf-8")
    return tmp_path


def test_a_finding_without_a_line_still_names_its_file(workspace: Path) -> None:
    result = runner.invoke(app, ["scan", str(workspace)])

    headline = next(line for line in result.output.splitlines() if "SVG generator comment" in line)
    assert "logo.svg" in headline


def test_a_finding_with_a_line_still_names_the_line(workspace: Path) -> None:
    """Paired with the test above: the path was added, the line was not lost."""

    result = runner.invoke(app, ["scan", str(workspace)])

    headline = next(
        line for line in result.output.splitlines() if "AI attribution in source comment" in line
    )
    assert "solver.py:2" in headline


def test_every_finding_the_terminal_prints_names_a_file(workspace: Path) -> None:
    """The general property, so a new detector cannot reintroduce the gap quietly."""

    import json

    rendered = runner.invoke(app, ["scan", str(workspace)])
    as_json = runner.invoke(app, ["scan", str(workspace), "--format", "json"])
    report = json.loads(as_json.output)

    assert report["findings"], "the fixture is meant to produce findings"
    for finding in report["findings"]:
        headline = next(
            (line for line in rendered.output.splitlines() if finding["title"] in line),
            None,
        )
        assert headline is not None, f"{finding['title']} was never printed"
        assert Path(finding["artifact_path"]).name in headline, (
            f"{finding['title']} printed without naming {finding['artifact_path']}"
        )
